version: "3.8"

services: 
  hadoop-master:
    image: uracilo/hadoop
    container_name: hadoop-master
    hostname: hadoop-master
    ports:
      - '50070:50070'
      - '8088:8088'
    stdin_open: true
    tty: true
  
  slave_1:
    image: uracilo/hadoop
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    stdin_open: true
    tty: true
    depends_on: 
      - hadoop-master
  
  slave_2:
    image: uracilo/hadoop
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    stdin_open: true
    tty: true
    depends_on: 
      - hadoop-master

  slave_3:
    image: uracilo/hadoop
    container_name: hadoop-slave3
    hostname: hadoop-slave3
    stdin_open: true
    tty: true
    depends_on: 
      - hadoop-master
  
  slave_4:
    image: uracilo/hadoop
    container_name: hadoop-slave4
    hostname: hadoop-slave4
    stdin_open: true
    tty: true
    depends_on: 
      - hadoop-master
  
  slave_5:
    image: uracilo/hadoop
    container_name: hadoop-slave5
    hostname: hadoop-slave5
    stdin_open: true
    tty: true
    depends_on: 
      - hadoop-master